// src/lib/mock-data.ts
import type { ListingCard } from '@/types'
import { LISTING_TYPES } from '@/config/constants'

export const mockListings: ListingCard[] = [
  {
    id: '1',
    slug: 'camp-etoiles-sahara-douz',
    type: LISTING_TYPES.CAMP,
    title: 'Camp Étoiles du Sahara',
    shortDescription: 'Une nuit magique sous les étoiles du désert avec dîner berbère traditionnel.',
    coverImage: {
      id: 'img-1',
      url: 'https://images.unsplash.com/photo-1509316785289-025f5b846b35?w=800&q=80',
      alt: 'Camp de nuit dans le désert sous les étoiles',
      order: 0,
      isCover: true,
    },
    address: { city: 'Douz', region: 'Kébili', country: 'Tunisia' },
    priceFrom: 18000,   // 180.00 TND in centimes
    rating: 4.9,
    reviewCount: 127,
    isFeatured: true,
    isVerified: true,
    duration: '1 nuit',
    tags: ['Désert', 'Étoiles', 'Dîner berbère'],
  },
  {
    id: '2',
    slug: 'guide-local-hamid-douz',
    type: LISTING_TYPES.GUIDE,
    title: 'Hamid — Guide Touareg Expert',
    shortDescription: 'Exploration authentique avec un guide né dans le désert. Circuits sur mesure.',
    coverImage: {
      id: 'img-2',
      url: 'https://images.unsplash.com/photo-1469854523086-cc02fe5d8800?w=800&q=80',
      alt: 'Guide local dans le désert de Douz',
      order: 0,
      isCover: true,
    },
    address: { city: 'Douz', region: 'Kébili', country: 'Tunisia' },
    priceFrom: 8000,    // 80.00 TND
    rating: 5.0,
    reviewCount: 89,
    isFeatured: false,
    isVerified: true,
    duration: 'Demi-journée',
    tags: ['Chameau', 'Dunes', 'Culture'],
  },
  {
    id: '3',
    slug: 'experience-poterie-nefta',
    type: LISTING_TYPES.STORE,
    title: 'Atelier Poterie Traditionnelle',
    shortDescription: 'Apprenez les techniques ancestrales de la poterie avec maître artisan.',
    coverImage: {
      id: 'img-3',
      url: 'https://images.unsplash.com/photo-1565193566173-7a0ee3dbe261?w=800&q=80',
      alt: 'Artisan potier au travail',
      order: 0,
      isCover: true,
    },
    address: { city: 'Nefta', region: 'Tozeur', country: 'Tunisia' },
    priceFrom: 4500,    // 45.00 TND
    rating: 4.7,
    reviewCount: 43,
    isFeatured: false,
    isVerified: true,
    duration: '3h',
    tags: ['Artisanat', 'Poterie', 'Culture'],
  },
  {
    id: '4',
    slug: 'circuit-4x4-chott-el-jerid',
    type: LISTING_TYPES.EXPERIENCE,
    title: 'Circuit 4×4 Chott el-Jérid',
    shortDescription: 'Traversée épique du plus grand lac salé d\'Afrique du Nord.',
    coverImage: {
      id: 'img-4',
      url: 'https://images.unsplash.com/photo-1542401886-65d6c61db217?w=800&q=80',
      alt: '4x4 sur le lac salé Chott el Jérid',
      order: 0,
      isCover: true,
    },
    address: { city: 'Tozeur', region: 'Tozeur', country: 'Tunisia' },
    priceFrom: 25000,   // 250.00 TND
    rating: 4.8,
    reviewCount: 61,
    isFeatured: true,
    isVerified: false,
    duration: '1 journée',
    tags: ['4x4', 'Aventure', 'Lac salé'],
  },
  {
    id: '5',
    slug: 'camp-tentes-luxe-ksar-ghilane',
    type: LISTING_TYPES.CAMP,
    title: 'Ksar Ghilane — Tentes de Luxe',
    shortDescription: 'Oasis mythique avec source thermale, tentes berbères équipées et vue imprenable.',
    coverImage: {
      id: 'img-5',
      url: 'https://images.unsplash.com/photo-1496545672447-f699b503d270?w=800&q=80',
      alt: 'Tentes de luxe dans l\'oasis de Ksar Ghilane',
      order: 0,
      isCover: true,
    },
    address: { city: 'Ksar Ghilane', region: 'Gabès', country: 'Tunisia' },
    priceFrom: 35000,   // 350.00 TND
    rating: 4.6,
    reviewCount: 204,
    isFeatured: true,
    isVerified: true,
    duration: '2 nuits',
    tags: ['Luxe', 'Oasis', 'Source thermale'],
  },
  {
    id: '6',
    slug: 'cours-cuisine-berbere-douz',
    type: LISTING_TYPES.EXPERIENCE,
    title: 'Cours de Cuisine Berbère',
    shortDescription: 'Préparez couscous, brik et makroudh avec Fatima dans sa maison traditionnelle.',
    coverImage: {
      id: 'img-6',
      url: 'https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?w=800&q=80',
      alt: 'Cours de cuisine traditionnelle tunisienne',
      order: 0,
      isCover: true,
    },
    address: { city: 'Douz', region: 'Kébili', country: 'Tunisia' },
    priceFrom: 6000,    // 60.00 TND
    rating: 4.9,
    reviewCount: 37,
    isFeatured: false,
    isVerified: true,
    duration: '4h',
    tags: ['Cuisine', 'Authentique', 'Famille'],
  },
]