import type { Story } from './types'

// Phase 2: replace with → fetch('/api/stories?limit=7')
// Slug structure mirrors future CMS: /stories/[slug]
// Images: Unsplash editorial desert photography — swap for owned assets pre-launch

export const storiesData: Story[] = [
  {
    id: 's-01',
    slug: 'nuit-bivouac-grand-erg-oriental',
    category: 'desert',
    issue: 'No. 01',
    title: 'Une nuit au cœur du Grand Erg Oriental',
    pullQuote: 'À 3h du matin, quand le vent s\'arrête, le silence du désert est si profond qu\'on entend battre son propre cœur.',
    excerpt: 'Hamid nous guide depuis l\'aube vers les dunes primaires que les touristes ne voient jamais. Bivouac, thé à la braise, et un ciel d\'une densité d\'étoiles qui rend les mots inutiles.',
    image: 'https://images.unsplash.com/photo-1509316785289-025f5b846b35?w=1200&q=85',
    imageAlt: 'Campement de nuit sous les étoiles dans les dunes du Sahara',
    author: { id: 'a-01', name: 'Hamid Belhaj', role: 'Guide touareg, Douz' },
    location: 'Grand Erg Oriental',
    readTime: '7 min',
    href: '/stories/nuit-bivouac-grand-erg-oriental',
    featured: true,
  },
  {
    id: 's-02',
    slug: 'mains-argile-fatima-potiere',
    category: 'artisan',
    issue: 'No. 02',
    title: 'Les mains de Fatima',
    pullQuote: 'Chaque bol porte la mémoire de cent potières avant moi.',
    excerpt: 'Dans son atelier de Guellala, Fatima perpétue un savoir-faire berbère vieux de trois millénaires. Une immersion dans la terre, la forme et le temps long.',
    image: 'https://images.unsplash.com/photo-1565193566173-7a0ee3dbe261?w=800&q=80',
    imageAlt: 'Artisane potière façonnant de l\'argile dans un atelier de Jerba',
    author: { id: 'a-02', name: 'Fatima Trabelsi', role: 'Maître artisane, Guellala' },
    location: 'Guellala, Jerba',
    readTime: '5 min',
    href: '/stories/mains-argile-fatima-potiere',
  },
  {
    id: 's-03',
    slug: 'festival-sahara-douz-memoire-nomade',
    category: 'festival',
    issue: 'No. 03',
    title: 'Le Festival du Sahara — mémoire nomade',
    pullQuote: 'Quatre jours où toute la tribu retrouve ses racines dans le bruit des tambours.',
    excerpt: 'Chaque décembre, Douz redevient capitale nomade. Fantasia, course de dromadaires, mariage traditionnel — une explosion culturelle qui déchire le silence du désert.',
    image: 'https://images.unsplash.com/photo-1469854523086-cc02fe5d8800?w=800&q=80',
    imageAlt: 'Cavaliers au Festival du Sahara de Douz avec dunes en arrière-plan',
    author: { id: 'a-03', name: 'Rédaction Mysira', role: 'Équipe éditoriale' },
    location: 'Douz, Kébili',
    readTime: '8 min',
    href: '/stories/festival-sahara-douz-memoire-nomade',
  },
  {
    id: 's-04',
    slug: 'couscous-au-bois-recette-berbere',
    category: 'gastronomy',
    issue: 'No. 04',
    title: 'Le couscous au bois de Khadija',
    pullQuote: 'La recette n\'est écrite nulle part. Elle passe de mère en fille depuis des siècles.',
    excerpt: 'Khadija prépare son couscous dans un kanoun en terre cuite, avec de l\'eau du puits et du beurre rance conservé dans une jarre. Un repas qui prend six heures et en laisse le souvenir toute une vie.',
    image: 'https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?w=800&q=80',
    imageAlt: 'Préparation traditionnelle du couscous dans une cuisine berbère',
    author: { id: 'a-04', name: 'Khadija Oueslati', role: 'Hôte culinaire, Douz' },
    location: 'Douz, Kébili',
    readTime: '6 min',
    href: '/stories/couscous-au-bois-recette-berbere',
  },
  {
    id: 's-05',
    slug: 'chott-el-jerid-traversee-4x4',
    category: 'desert',
    issue: 'No. 05',
    title: 'Traversée du Chott el-Jérid',
    pullQuote: 'Le lac salé réfléchit le ciel comme un miroir fracturé — on ne sait plus où finit la terre.',
    excerpt: 'En 4×4 à l\'aube, quand la surface du Chott se teinte de rose et d\'or, on comprend pourquoi les anciens croyaient que ce lieu était la frontière entre deux mondes.',
    image: 'https://images.unsplash.com/photo-1542401886-65d6c61db217?w=800&q=80',
    imageAlt: 'Reflets du ciel sur la surface du lac salé Chott el-Jérid au coucher du soleil',
    author: { id: 'a-05', name: 'Anouar Slim', role: 'Guide 4×4, Tozeur' },
    location: 'Chott el-Jérid, Tozeur',
    readTime: '5 min',
    href: '/stories/chott-el-jerid-traversee-4x4',
  },
  {
    id: 's-06',
    slug: 'tissage-berbere-tapis-memoire',
    category: 'artisan',
    issue: 'No. 06',
    title: 'Un tapis est une mémoire',
    pullQuote: 'Chaque symbole est une lettre. Un tapis ancien, c\'est une lettre d\'amour que personne ne peut lire.',
    excerpt: 'Les tapis berbères du sud tunisien ne sont pas des décorations — ce sont des archives. Rencontre avec les tisserandes d\'El-Hamma qui brodent leur histoire dans la laine.',
    image: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800&q=80',
    imageAlt: 'Tisserande berbère travaillant sur un métier à tisser traditionnel',
    author: { id: 'a-06', name: 'Leila Gharbi', role: 'Artisane tisserande, El-Hamma' },
    location: 'El-Hamma, Gabès',
    readTime: '4 min',
    href: '/stories/tissage-berbere-tapis-memoire',
  },
  {
    id: 's-07',
    slug: 'ksar-ghilane-oasis-source-thermale',
    category: 'nomadic',
    issue: 'No. 07',
    title: 'Ksar Ghilane, l\'oasis qui guérit',
    pullQuote: 'On arrive épuisé par la piste. On repart différent.',
    excerpt: 'À l\'extrémité du Grand Erg Oriental, une source thermale jaillit du sable depuis des millénaires. Les caravaniers s\'y arrêtaient pour soigner leurs bêtes. On s\'y arrête pour soigner son âme.',
    image: 'https://images.unsplash.com/photo-1496545672447-f699b503d270?w=800&q=80',
    imageAlt: 'Source thermale naturelle entourée de palmiers dans l\'oasis de Ksar Ghilane',
    author: { id: 'a-07', name: 'Sami Chaabane', role: 'Guide camp, Ksar Ghilane' },
    location: 'Ksar Ghilane, Gabès',
    readTime: '6 min',
    href: '/stories/ksar-ghilane-oasis-source-thermale',
  },
]